[
  (basic_category)
  (ref_spec)
  (preamble)
  (items_block)
  (item)
  (definition_block)
  (description_block)
  (remark_block)
  (group)
  (extended)
  (compound)
  (repetitive)
  (explicit)
  (element)
  (content_table)
  (content_dependent)
  (content_case)
  (dependent_variation)
  (variation_case)
  (uap_block)
  (uaps_block)
  (uap_variations_block)
  (uap_variation)
  (uap_case_block)
  (uap_case_row)
] @fold

(#trim! @fold)
