[
  (basic_category)
  (ref_spec)
  (preamble)
  (items_block)
  (item)
  (definition_block)
  (description_block)
  (remark_block)
  (group)
  (extended)
  (compound)
  (repetitive)
  (explicit)
  (element)
  (content_table)
  (content_dependent)
  (content_case)
  (dependent_variation)
  (variation_case)
  (uap_block)
  (uaps_block)
  (uap_variations_block)
  (uap_variation)
  (uap_case_block)
  (uap_case_row)
] @indent

[
  (basic_category)
  (ref_spec)
  (preamble)
  (items_block)
  (item)
  (definition_block)
  (description_block)
  (remark_block)
  (group)
  (extended)
  (compound)
  (repetitive)
  (explicit)
  (element)
  (content_table)
  (content_dependent)
  (content_case)
  (dependent_variation)
  (variation_case)
  (uap_block)
  (uaps_block)
  (uap_variations_block)
  (uap_variation)
  (uap_case_block)
  (uap_case_row)
] @indent.begin

[
  (basic_category)
  (ref_spec)
  (preamble)
  (items_block)
  (item)
  (definition_block)
  (description_block)
  (remark_block)
  (group)
  (extended)
  (compound)
  (repetitive)
  (explicit)
  (element)
  (content_table)
  (content_dependent)
  (content_case)
  (dependent_variation)
  (variation_case)
  (uap_block)
  (uaps_block)
  (uap_variations_block)
  (uap_variation)
  (uap_case_block)
  (uap_case_row)
] @extend

; Editing fallbacks for incomplete indentation-sensitive blocks.
; While typing, Helix may see one large ERROR node until the first child line is
; indented. These captures let Enter/o still indent after block-opening lines.
(ERROR "preamble" @indent @extend)
(ERROR "items" @indent @extend)
(ERROR "definition" @indent @extend)
(ERROR "description" @indent @extend)
(ERROR "remark" @indent @extend)
(ERROR "group" @indent @extend)
(ERROR "extended" @indent @extend)
(ERROR "compound" @indent @extend)
(ERROR "compound" (byte_size) @indent @extend)
(ERROR "compound" "fx" @indent @extend)
(ERROR "repetitive" @indent @extend)
(ERROR "repetitive" (byte_size) @indent @extend)
(ERROR "repetitive" "fx" @indent @extend)
(ERROR "element" @indent @extend)
(ERROR "element" (bit_size) @indent @extend)
(ERROR "table" @indent @extend)
(ERROR "variations" @indent @extend)
(ERROR "uap" @indent @extend)
(ERROR "uaps" @indent @extend)
(ERROR "case" @indent @extend)
(ERROR "case" (item_path) @indent @extend)
(ERROR "case" (item_path_tuple) @indent @extend)
(ERROR (case_key) ":" @indent @extend)
(ERROR (case_key) @indent.always @extend)
(ERROR (case_key_tuple) ":" @indent @extend)
(ERROR (case_key_tuple) @indent.always @extend)
(ERROR (default_case) @indent.always @extend)
(ERROR (default_case) ":" @indent.always @extend)
(content_case (default_case) ":" @indent.always @extend)
(ERROR (item_name) (string) @indent @extend)

; UAPS variation names such as `plot` and `track` are dynamic. While typing the
; first child below them, Helix sees the variation body as an ERROR node.
(ERROR (uap_name) @indent @extend)

((text) @indent.always @extend
  (#match? @indent.always ":$"))

[
  (content_raw)
  (content_string)
  (content_integer)
  (content_quantity)
  (content_bds)
] @extend.prevent-once
